#!/bin/bash
declare -a choices=("100%"
                    "75%"
                    "50%"
                    "25%"
                    "mute"
                    "unmute"
                    )


userChoice=$(echo "$(printf '%s\n' "${choices[@]}")" | dmenu -l 20 -p 'sound: ')


case "$userChoice" in
  "")
    ;;
  "mute")
    amixer -c 2 sset PCM mute
    ;;
  "unmute")
    amixer  -c 2 sset PCM unmute
    ;;
  *)
    amixer -c 2 sset PCM $userChoice
    amixer -c 2 sset PCM unmute
    ;;
esac
