#!/bin/bash

promptedText="Calc: "

calcPrompt() {
  userInput=$(echo "quit" | dmenu -p "$promptedText")
  if [[ $userInput != '' && $userInput != "quit" ]]; then
    promptedText=$(calc $(echo $userInput))
  fi
}

calcPrompt
while [[ $userInput != '' && $userInput != "quit" ]]; do
  calcPrompt
done
